server {
    listen 80;
    server_name chat.wmavishka.me;

    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name chat.wmavishka.me;

    ssl_certificate /etc/letsencrypt/live/chat.wmavishka.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.wmavishka.me/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /socket.io/ {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
